### ISSUE TITLE
Drupal 9 compatability

### ISSUE THREAD

**Issue by RodBruce** [mjordan/ip_range_access#8]
When I try to install the module on an Islandora site using Drupal 9 I get the error:
`Unable to install modules: module 'ip_range_access' is incompatible with this version of Drupal core.`

I added :
`core_version_requirement: ^8 || ^9`

To the ip_range_access.info.yml file and was then able to install the module.

Thanks

**Comment by mjordan** [comment]
Changed to `core_version_requirement: ^9 || ^10.
